### ISSUE TITLE
Remove hardcoded terraform version

### ISSUE THREAD

**Issue by tbyerly** [JeffGiroux/f5_terraform#20]
in f5_terraform/AWS/Infrastructure-only/main.tf

hardcoded version no longer works.  Id just let it go to default

**Comment by JeffGiroux** [comment]
What errors did you receive?

**Comment by tbyerly** [comment]
Initializing modules...

Downloading github.com/f5devcentral/f5-digital-customer-engagement-center?ref=v1.1.0 for aws_network...

- aws_network in .terraform/modules/aws_network/modules/aws/terraform/network/min

╷

│ Error: Unsupported Terraform Core version

│

│   on main.tf line 5, in terraform:

│    5:   required_version = "~> 0.14"

│

│ This configuration does not support Terraform version 1.0.4. To proceed, either choose another supported Terraform version or update this version constraint. Version constraints are normally set for good reason, so

│ updating the constraint may lead to other errors or unexpected behavior.





From: Jeff ***@***.***>
Date: Saturday, August 7, 2021 at 3:16 PM
To: JeffGiroux/f5_terraform ***@***.***>
Cc: Ted Byerly ***@***.***>, Author ***@***.***>
Subject: Re: [JeffGiroux/f5_terraform] Remove hardcoded terraform version (#20)

EXTERNAL MAIL: ***@***.***

What errors did you receive?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffGiroux%2Ff5_terraform%2Fissues%2F20%23issuecomment-894712570&data=04%7C01%7CT.Byerly%40f5.com%7Cb1643104eb134c92c02308d959f109ba%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637639714072552518%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=G6knIgYjrDk8WZ1An43TmHCn48TmYXlwV3FxPiMI3Nk%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAHLSTN7BJQPFLTPXKSY6IQTT3WWEPANCNFSM5BXY32TQ&data=04%7C01%7CT.Byerly%40f5.com%7Cb1643104eb134c92c02308d959f109ba%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637639714072562513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eE9gAXEgHWVNdwaGLe1fHKbg2239hBOYGUC4TV6%2FQuo%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CT.Byerly%40f5.com%7Cb1643104eb134c92c02308d959f109ba%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637639714072562513%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wO13FerZEzg2g%2FBYTnVXV9UDBYAfc2sbeQsyC0W0a%2BI%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CT.Byerly%40f5.com%7Cb1643104eb134c92c02308d959f109ba%7Cdd3dfd2f6a3b40d19be0bf8327d81c50%7C0%7C0%7C637639714072572511%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=oLju1B1rAsqseKUBpOFmXj0YdapyDqpjIPpnYpgw9gE%3D&reserved=0>.

**Comment by JeffGiroux** [comment]
I will need to keep pinning on there as to avoid problems with terraform versions in the future not working with the current repo. From the error, looks like your terraform client is 1.x version whereas the repo pins to the 0.14.x version. You will need to grab terraform 0.14.x to work this repo.

I use tfenv to install multiple versions of terraform on my macbook laptop. Install https://github.com/tfutils/tfenv, then install a second version of terraform...for this repo...something in 0.14.x.

**Comment by tbyerly** [comment]
Thank you ... now that I read it and understand I will use tfenv.
