### ISSUE TITLE
DNS Name resolution is not working 

### ISSUE THREAD

**Issue by rohitandani** [JeffGiroux/f5_terraform#38]
The script is working fine for deployment however instances are not getting the azure managed dns name for the instances because of that i can not ping instances using dns name.

the local host file has entry to resolve the mgmt ip address on 127.0.0.1 instance of local domain name . 

2 fixes are needed
1) Assign the a valid hostname e.g xx.southeastasia.cloudapp.azure.com which should be coming from Azure managed DNS 
2) Hostfile should be having only valid entry to map the mgmt ip address with the valid hostname

**Comment by JeffGiroux** [comment]
It appears hostname does not relate to VM assigned name on Azure side, so therefore DNS does not match name to IP. Not sure...need to dig. Sounds related to forcing domain suffixes in previous ticket.

https://github.com/F5Networks/f5-azure-arm-templates-v2/issues/3

But if you force suffix, which one, and which one resolves in the VNET in which you deploy services. Again, need to dig...currently there is no deployment issues. Just a dns resolution as everything else seems to be onboarding correctly. I force a DNS suffix to be chosen on my GCP templates...might have to do that based on what's in the Vnet properties or other.

**Comment by JeffGiroux** [comment]
https://docs.microsoft.com/en-us/answers/questions/748724/azure-vm-scale-set-custom-vm-names.html

**Comment by JeffGiroux** [comment]
Revamped code to use BIG-IP module. Please open new issue if problem persist in new code version.
