### ISSUE TITLE
gcp-onboard fails to create non admin user account

### ISSUE THREAD

**Issue by vinnie357** [JeffGiroux/f5_terraform#5]
folder: GCP/HA_via_api

Intermittently, the custom account admin account isn't created.

symptoms: 

   can't login with sshkey or password after creation. have to use the "admin" account which should be disabled.

```bash
[admin@mydemo-f5vm01:Active:Standalone] ~ # cat /var/log/cloud/onboard.log | grep -A 20 Updating
Updating admin account
Syntax Error: "bash" unknown property
Copying SSH key
Admin account updated

```

code:

https://github.com/JeffGiroux/f5_terraform/blob/master/GCP/HA_via_api/onboard.tpl#L407
```bash
# Create admin account and password
echo "Updating admin account"
if [[ $admin_username != "admin" ]]; then
  tmsh create auth user $admin_username password "$admin_password" shell bash partition-access add { all-partitions { role admin } };
else
  tmsh modify auth user admin password "$admin_password";
fi
```

I don't see the difference from mine, but I haven't hit this, maybe something in 15.1?
https://github.com/vinnie357/bigip-bash-onboard-templates/blob/master/gcp/onboard.sh#L100

**Comment by vinnie357** [comment]
appears to be two issues combining to create the failure.
https://github.com/JeffGiroux/f5_terraform/blob/master/GCP/HA_via_api/onboard.tpl#L405
```bash
CREDS="admin:"$admin_password
```
vs:

```bash
CREDS="admin:$admin_password"
```
also the service account required ownership of the secret. without this it cause the password field to fail silently, and prevent all the remaining tasks from completing.

**Comment by JeffGiroux** [comment]
@vinnie357 

service account requirements for permissions are listed in README. Do I need to add another role besides the current list?

from readme...
```
My service account for Terraform deployments in GCP uses the following roles:
Compute Admin
Storage Admin
Service Account User
Service Account Admin
Project IAM Admin
```

As for 15.1, I just tested all my folder options (standalone, ha, autoscale, etc) and none failed to create admin after running through multiple times. I have not modified the CREDS section of code yet. Are you still seeing this issue? Should I modify code any to optimize and avoid?

**Comment by vinnie357** [comment]
don't worry about it, long past this :D
